export const VIEWBOX_WIDTH = 100;
export const VIEWBOX_HEIGHT = 60;

const createConstellation = ({
  id,
  name,
  accent,
  headline,
  region,
  bestSeen,
  knownFor,
  description,
  label,
  stars,
  connections,
}) => ({
  id,
  name,
  accent,
  headline,
  region,
  bestSeen,
  knownFor,
  description,
  label,
  stars,
  connections,
});

export const CONSTELLATIONS = [
  createConstellation({
    id: "draco",
    name: "Draco",
    accent: "#78ffb7",
    headline: "A long northern coil wrapped around the pole.",
    region: "Far northern sky",
    bestSeen: "May to August",
    knownFor: "Its winding shape and ancient pole-star history.",
    description:
      "Draco snakes between the familiar northern patterns, with a body that feels more like a path than a single figure.",
    label: { x: 16.4, y: 9.2, align: "start" },
    stars: [
      { id: "aldhibah", name: "Aldhibah", x: 9.8, y: 10.8, size: 1.2 },
      { id: "thuban", name: "Thuban", x: 12.8, y: 12.9, size: 1.4 },
      { id: "edasich", name: "Edasich", x: 16.8, y: 14.5, size: 1.1 },
      { id: "kuma", name: "Kuma", x: 21.8, y: 12.9, size: 1.1 },
      { id: "grumium", name: "Grumium", x: 24.5, y: 10.9, size: 1.3 },
      { id: "rastaban", name: "Rastaban", x: 28.2, y: 10.4, size: 1.5 },
      { id: "eltanin", name: "Eltanin", x: 30.0, y: 8.8, size: 1.8 },
    ],
    connections: [
      ["aldhibah", "thuban"],
      ["thuban", "edasich"],
      ["edasich", "kuma"],
      ["kuma", "grumium"],
      ["grumium", "rastaban"],
      ["rastaban", "eltanin"],
    ],
  }),
  createConstellation({
    id: "ursa-major",
    name: "Ursa Major",
    accent: "#9bd6ff",
    headline: "The northern giant with the most famous asterism in the sky.",
    region: "Northern sky",
    bestSeen: "March to June",
    knownFor: "The Big Dipper and easy north-sky navigation.",
    description:
      "Ursa Major dominates the northern spring sky. Its bowl and handle are iconic, but the full constellation sprawls much wider.",
    label: { x: 23.4, y: 11.2, align: "start" },
    stars: [
      { id: "dubhe", name: "Dubhe", x: 21.5, y: 13.5, size: 1.9 },
      { id: "merak", name: "Merak", x: 23.2, y: 16.8, size: 1.7 },
      { id: "phecda", name: "Phecda", x: 27.6, y: 17.6, size: 1.6 },
      { id: "megrez", name: "Megrez", x: 29.1, y: 15.1, size: 1.4 },
      { id: "alioth", name: "Alioth", x: 33.2, y: 14.2, size: 1.8 },
      { id: "mizar", name: "Mizar", x: 36.2, y: 12.6, size: 1.6 },
      { id: "alkaid", name: "Alkaid", x: 39.2, y: 11.2, size: 1.7 },
    ],
    connections: [
      ["dubhe", "merak"],
      ["merak", "phecda"],
      ["phecda", "megrez"],
      ["megrez", "dubhe"],
      ["megrez", "alioth"],
      ["alioth", "mizar"],
      ["mizar", "alkaid"],
    ],
  }),
  createConstellation({
    id: "bootes",
    name: "Bootes",
    accent: "#ffb47a",
    headline: "A tall kite shape led by brilliant Arcturus.",
    region: "Northern spring sky",
    bestSeen: "April to July",
    knownFor: "Arcturus and its shepherd-like outline.",
    description:
      "Bootes feels lean and fast on the map, anchored by Arcturus and stretched into a long celestial kite.",
    label: { x: 35.2, y: 18.8, align: "start" },
    stars: [
      { id: "nekkar", name: "Nekkar", x: 36.1, y: 13.1, size: 1.2 },
      { id: "seginus", name: "Seginus", x: 35.4, y: 16.6, size: 1.1 },
      { id: "izar", name: "Izar", x: 39.2, y: 15.2, size: 1.4 },
      { id: "arcturus", name: "Arcturus", x: 41.0, y: 18.8, size: 2.2 },
      { id: "rho", name: "Rho Bootis", x: 43.3, y: 16.1, size: 1.0 },
    ],
    connections: [
      ["nekkar", "seginus"],
      ["seginus", "izar"],
      ["izar", "arcturus"],
      ["arcturus", "rho"],
      ["rho", "seginus"],
    ],
  }),
  createConstellation({
    id: "hercules",
    name: "Hercules",
    accent: "#ffe089",
    headline: "A broad keystone with limbs stretching around it.",
    region: "Northern summer sky",
    bestSeen: "June to September",
    knownFor: "The Keystone asterism and rich telescope fields.",
    description:
      "Hercules is more about structure than a single bright star. Its central keystone gives the whole figure its identity.",
    label: { x: 41.6, y: 21.0, align: "start" },
    stars: [
      { id: "sarins", name: "Sarin", x: 41.1, y: 18.0, size: 1.0 },
      { id: "zeta", name: "Zeta Herculis", x: 43.1, y: 20.1, size: 1.3 },
      { id: "eta", name: "Eta Herculis", x: 46.4, y: 19.8, size: 1.2 },
      { id: "pi", name: "Pi Herculis", x: 47.6, y: 23.3, size: 1.2 },
      { id: "epsilon", name: "Epsilon Herculis", x: 44.2, y: 24.2, size: 1.2 },
      { id: "ras", name: "Rasalgethi", x: 49.6, y: 26.0, size: 1.6 },
    ],
    connections: [
      ["zeta", "eta"],
      ["eta", "pi"],
      ["pi", "epsilon"],
      ["epsilon", "zeta"],
      ["zeta", "sarins"],
      ["pi", "ras"],
    ],
  }),
  createConstellation({
    id: "leo",
    name: "Leo",
    accent: "#ffb155",
    headline: "A bright lion split into a sickle and a tail.",
    region: "Zodiacal spring sky",
    bestSeen: "March to May",
    knownFor: "Regulus and the classic lion sickle.",
    description:
      "Leo reads quickly even in a stylized map. The front half hooks into a sickle, while Denebola pulls the tail outward.",
    label: { x: 48.2, y: 12.7, align: "start" },
    stars: [
      { id: "regulus", name: "Regulus", x: 48.4, y: 20.2, size: 2.0 },
      { id: "chort", name: "Chort", x: 50.4, y: 15.6, size: 1.2 },
      { id: "adhafera", name: "Adhafera", x: 51.8, y: 17.3, size: 1.2 },
      { id: "eta", name: "Eta Leonis", x: 52.1, y: 19.0, size: 1.1 },
      { id: "algieba", name: "Algieba", x: 54.6, y: 16.6, size: 1.5 },
      { id: "zosma", name: "Zosma", x: 55.7, y: 14.0, size: 1.2 },
      { id: "denebola", name: "Denebola", x: 59.1, y: 12.2, size: 1.6 },
    ],
    connections: [
      ["regulus", "eta"],
      ["eta", "adhafera"],
      ["adhafera", "algieba"],
      ["algieba", "chort"],
      ["chort", "regulus"],
      ["algieba", "zosma"],
      ["zosma", "denebola"],
    ],
  }),
  createConstellation({
    id: "virgo",
    name: "Virgo",
    accent: "#ffd57d",
    headline: "A wide spring figure led by Spica.",
    region: "Equatorial sky",
    bestSeen: "April to June",
    knownFor: "Spica and its huge sweep across galaxy-rich skies.",
    description:
      "Virgo sprawls across a broad patch of sky. It feels less like a rigid icon and more like a large network of bright waypoints.",
    label: { x: 60.2, y: 19.2, align: "start" },
    stars: [
      { id: "vindemiatrix", name: "Vindemiatrix", x: 59.8, y: 20.2, size: 1.5 },
      { id: "porrima", name: "Porrima", x: 61.5, y: 24.5, size: 1.4 },
      { id: "zaniah", name: "Zaniah", x: 64.1, y: 21.4, size: 1.1 },
      { id: "auva", name: "Auva", x: 63.6, y: 25.6, size: 1.1 },
      { id: "heze", name: "Heze", x: 68.9, y: 22.6, size: 1.1 },
      { id: "spica", name: "Spica", x: 66.8, y: 29.4, size: 2.1 },
    ],
    connections: [
      ["vindemiatrix", "porrima"],
      ["porrima", "auva"],
      ["auva", "spica"],
      ["porrima", "zaniah"],
      ["zaniah", "heze"],
      ["heze", "spica"],
    ],
  }),
  createConstellation({
    id: "ophiuchus",
    name: "Ophiuchus",
    accent: "#c3ff7f",
    headline: "A broad summer figure holding the serpent.",
    region: "Equatorial summer sky",
    bestSeen: "June to August",
    knownFor: "Its huge footprint and serpent-bearer shape.",
    description:
      "Ophiuchus is massive and slightly awkward in the best way. It bridges the zodiac and the Milky Way with a wide, human-like frame.",
    label: { x: 48.4, y: 28.4, align: "start" },
    stars: [
      { id: "rasalhague", name: "Rasalhague", x: 54.4, y: 27.4, size: 1.9 },
      { id: "cebalrai", name: "Cebalrai", x: 52.6, y: 30.2, size: 1.3 },
      { id: "yed-prior", name: "Yed Prior", x: 56.3, y: 31.6, size: 1.2 },
      { id: "yed-posterior", name: "Yed Posterior", x: 58.4, y: 32.4, size: 1.2 },
      { id: "sabik", name: "Sabik", x: 60.4, y: 35.2, size: 1.4 },
      { id: "zeta", name: "Zeta Ophiuchi", x: 51.1, y: 34.1, size: 1.4 },
      { id: "delta", name: "Delta Ophiuchi", x: 47.8, y: 32.6, size: 1.2 },
    ],
    connections: [
      ["delta", "cebalrai"],
      ["cebalrai", "rasalhague"],
      ["cebalrai", "yed-prior"],
      ["yed-prior", "yed-posterior"],
      ["yed-posterior", "sabik"],
      ["sabik", "zeta"],
      ["zeta", "delta"],
    ],
  }),
  createConstellation({
    id: "pegasus",
    name: "Pegasus",
    accent: "#d7b6ff",
    headline: "A giant square opening into a winged frame.",
    region: "Autumn sky",
    bestSeen: "September to November",
    knownFor: "The Great Square and easy autumn orientation.",
    description:
      "Pegasus is instantly readable from the Great Square, making it a natural anchor for an interactive sky map.",
    label: { x: 69.8, y: 11.0, align: "start" },
    stars: [
      { id: "markab", name: "Markab", x: 70.4, y: 14.1, size: 1.7 },
      { id: "scheat", name: "Scheat", x: 75.4, y: 12.2, size: 1.7 },
      { id: "algenib", name: "Algenib", x: 80.8, y: 14.4, size: 1.5 },
      { id: "enif", name: "Enif", x: 76.4, y: 18.3, size: 1.8 },
      { id: "homam", name: "Homam", x: 72.9, y: 17.0, size: 1.2 },
    ],
    connections: [
      ["markab", "scheat"],
      ["scheat", "algenib"],
      ["algenib", "enif"],
      ["enif", "markab"],
      ["markab", "homam"],
      ["homam", "enif"],
    ],
  }),
  createConstellation({
    id: "cassiopeia",
    name: "Cassiopeia",
    accent: "#f0a8ff",
    headline: "A clean W shape bright enough for casual scanning.",
    region: "Northern circumpolar sky",
    bestSeen: "September to January",
    knownFor: "Its sharp zigzag and reliable northern presence.",
    description:
      "Cassiopeia is compact, bold, and graphic. It behaves almost like a logo in the sky.",
    label: { x: 78.2, y: 4.9, align: "start" },
    stars: [
      { id: "schedar", name: "Schedar", x: 78.2, y: 8.1, size: 1.8 },
      { id: "caph", name: "Caph", x: 81.1, y: 7.5, size: 1.4 },
      { id: "gamma", name: "Gamma Cassiopeiae", x: 84.4, y: 8.4, size: 1.6 },
      { id: "ruchbah", name: "Ruchbah", x: 87.2, y: 7.2, size: 1.2 },
      { id: "segin", name: "Segin", x: 90.1, y: 8.7, size: 1.3 },
    ],
    connections: [
      ["schedar", "caph"],
      ["caph", "gamma"],
      ["gamma", "ruchbah"],
      ["ruchbah", "segin"],
    ],
  }),
  createConstellation({
    id: "aquarius",
    name: "Aquarius",
    accent: "#79f1ff",
    headline: "A broad autumn water-bearer built from linked zigzags.",
    region: "Southern autumn sky",
    bestSeen: "September to November",
    knownFor: "Its huge footprint and zodiac status.",
    description:
      "Aquarius is subtle in brightness but large in presence. It reads as a field of linked water-channel stars more than a single rigid silhouette.",
    label: { x: 82.6, y: 22.2, align: "start" },
    stars: [
      { id: "sadachbia", name: "Sadachbia", x: 82.6, y: 26.1, size: 1.2 },
      { id: "sadalmelik", name: "Sadalmelik", x: 86.2, y: 24.5, size: 1.6 },
      { id: "sadalsuud", name: "Sadalsuud", x: 90.5, y: 24.9, size: 1.7 },
      { id: "albali", name: "Albali", x: 88.2, y: 28.7, size: 1.1 },
      { id: "skat", name: "Skat", x: 92.8, y: 29.6, size: 1.5 },
      { id: "ancha", name: "Ancha", x: 84.8, y: 30.0, size: 1.2 },
    ],
    connections: [
      ["sadachbia", "sadalmelik"],
      ["sadalmelik", "sadalsuud"],
      ["sadalmelik", "albali"],
      ["albali", "skat"],
      ["sadachbia", "ancha"],
      ["ancha", "skat"],
    ],
  }),
  createConstellation({
    id: "pisces",
    name: "Pisces",
    accent: "#95bfff",
    headline: "Two fish tied together by a long celestial cord.",
    region: "Autumn zodiac",
    bestSeen: "October to December",
    knownFor: "The knot at Alrescha and its twin-stream shape.",
    description:
      "Pisces is faint but elegant. In an interactive view, its long tether between two groups becomes easier to appreciate.",
    label: { x: 87.2, y: 13.7, align: "start" },
    stars: [
      { id: "alrescha", name: "Alrescha", x: 87.4, y: 16.9, size: 1.4 },
      { id: "torcular", name: "Torcular", x: 90.0, y: 18.6, size: 1.0 },
      { id: "omega", name: "Omega Piscium", x: 93.5, y: 20.0, size: 0.9 },
      { id: "fum", name: "Fumalsamakah", x: 96.3, y: 18.4, size: 1.1 },
      { id: "delta", name: "Delta Piscium", x: 95.1, y: 15.1, size: 1.1 },
    ],
    connections: [
      ["alrescha", "torcular"],
      ["torcular", "omega"],
      ["omega", "fum"],
      ["torcular", "delta"],
    ],
  }),
  createConstellation({
    id: "orion",
    name: "Orion",
    accent: "#86b6ff",
    headline: "The hunter, compact and instantly recognizable.",
    region: "Equatorial winter sky",
    bestSeen: "December to March",
    knownFor: "The belt stars and bright winter presence.",
    description:
      "Orion is not one of the largest constellations, but it is too iconic to leave out of a first pass. It gives the map an instantly familiar anchor.",
    label: { x: 69.2, y: 27.3, align: "start" },
    stars: [
      { id: "betelgeuse", name: "Betelgeuse", x: 69.5, y: 29.4, size: 2.1 },
      { id: "bellatrix", name: "Bellatrix", x: 73.6, y: 30.1, size: 1.6 },
      { id: "alnitak", name: "Alnitak", x: 71.1, y: 33.3, size: 1.4 },
      { id: "alnilam", name: "Alnilam", x: 73.4, y: 33.7, size: 1.5 },
      { id: "mintaka", name: "Mintaka", x: 75.5, y: 33.0, size: 1.3 },
      { id: "saiph", name: "Saiph", x: 72.0, y: 37.6, size: 1.4 },
      { id: "rigel", name: "Rigel", x: 76.5, y: 37.1, size: 2.0 },
    ],
    connections: [
      ["betelgeuse", "bellatrix"],
      ["betelgeuse", "alnitak"],
      ["bellatrix", "mintaka"],
      ["alnitak", "alnilam"],
      ["alnilam", "mintaka"],
      ["alnitak", "saiph"],
      ["mintaka", "rigel"],
      ["saiph", "rigel"],
    ],
  }),
  createConstellation({
    id: "hydra",
    name: "Hydra",
    accent: "#8ce6d5",
    headline: "The largest constellation, stretched like a river-serpent.",
    region: "Equatorial sky",
    bestSeen: "March to May",
    knownFor: "Its sheer length and lone bright heart, Alphard.",
    description:
      "Hydra behaves like a horizon-spanning path. It does not sit in one patch of sky so much as drift through several constellations at once.",
    label: { x: 24.4, y: 31.5, align: "start" },
    stars: [
      { id: "nu", name: "Nu Hydrae", x: 24.5, y: 33.9, size: 1.0 },
      { id: "gamma", name: "Gamma Hydrae", x: 28.2, y: 35.8, size: 1.2 },
      { id: "alphard", name: "Alphard", x: 34.4, y: 38.8, size: 2.0 },
      { id: "xi", name: "Xi Hydrae", x: 39.4, y: 40.1, size: 1.1 },
      { id: "mu", name: "Mu Hydrae", x: 45.2, y: 42.0, size: 1.0 },
      { id: "pi", name: "Pi Hydrae", x: 51.6, y: 43.1, size: 1.0 },
      { id: "upsilon", name: "Upsilon Hydrae", x: 58.0, y: 43.6, size: 1.0 },
      { id: "eta", name: "Eta Hydrae", x: 65.7, y: 42.9, size: 1.0 },
      { id: "zeta", name: "Zeta Hydrae", x: 70.2, y: 40.8, size: 1.1 },
    ],
    connections: [
      ["nu", "gamma"],
      ["gamma", "alphard"],
      ["alphard", "xi"],
      ["xi", "mu"],
      ["mu", "pi"],
      ["pi", "upsilon"],
      ["upsilon", "eta"],
      ["eta", "zeta"],
    ],
  }),
  createConstellation({
    id: "centaurus",
    name: "Centaurus",
    accent: "#ff92be",
    headline: "A southern giant with two of the sky's brightest guide stars.",
    region: "Southern Milky Way",
    bestSeen: "April to June",
    knownFor: "Alpha and Beta Centauri and its huge southern spread.",
    description:
      "Centaurus feels muscular and radiant on the map, with a dense southern footprint and bright guide stars that pull the eye.",
    label: { x: 38.0, y: 41.6, align: "start" },
    stars: [
      { id: "menkent", name: "Menkent", x: 38.2, y: 44.0, size: 1.3 },
      { id: "alpha", name: "Alpha Centauri", x: 40.8, y: 46.4, size: 2.2 },
      { id: "beta", name: "Beta Centauri", x: 43.8, y: 45.0, size: 2.0 },
      { id: "theta", name: "Theta Centauri", x: 46.1, y: 43.2, size: 1.2 },
      { id: "iota", name: "Iota Centauri", x: 48.4, y: 45.6, size: 1.1 },
      { id: "mu", name: "Mu Centauri", x: 47.5, y: 49.0, size: 1.2 },
    ],
    connections: [
      ["menkent", "alpha"],
      ["alpha", "beta"],
      ["beta", "theta"],
      ["theta", "iota"],
      ["iota", "mu"],
      ["beta", "mu"],
    ],
  }),
  createConstellation({
    id: "scorpius",
    name: "Scorpius",
    accent: "#ff7b68",
    headline: "A hooked body with Antares burning at the center.",
    region: "Southern summer Milky Way",
    bestSeen: "June to August",
    knownFor: "Antares, the curved tail, and a vivid low-sky silhouette.",
    description:
      "Scorpius reads like motion. Even in a stylized map it keeps its claw, heart, and curling tail intact.",
    label: { x: 58.0, y: 36.5, align: "start" },
    stars: [
      { id: "jabbah", name: "Jabbah", x: 61.7, y: 38.2, size: 1.0 },
      { id: "graffias", name: "Graffias", x: 58.2, y: 39.1, size: 1.4 },
      { id: "dschubba", name: "Dschubba", x: 60.6, y: 40.2, size: 1.4 },
      { id: "antares", name: "Antares", x: 62.9, y: 42.3, size: 2.2 },
      { id: "sargas", name: "Sargas", x: 66.1, y: 45.1, size: 1.7 },
      { id: "lesath", name: "Lesath", x: 68.2, y: 45.4, size: 1.3 },
      { id: "shaula", name: "Shaula", x: 69.2, y: 46.7, size: 1.8 },
    ],
    connections: [
      ["graffias", "dschubba"],
      ["dschubba", "antares"],
      ["antares", "sargas"],
      ["sargas", "lesath"],
      ["lesath", "shaula"],
      ["jabbah", "dschubba"],
    ],
  }),
  createConstellation({
    id: "vela",
    name: "Vela",
    accent: "#66e6ff",
    headline: "The sail of Argo and the namesake of this map.",
    region: "Southern sky",
    bestSeen: "February to April",
    knownFor: "Its history as part of Argo Navis and its bright southern spread.",
    description:
      "Vela is the hero constellation for this project. It inherits the old ship myth, then breaks it into a modern navigational pattern of sail points and rigging lines.",
    label: { x: 54.2, y: 42.0, align: "start" },
    stars: [
      { id: "gamma", name: "Gamma Velorum", x: 55.1, y: 44.4, size: 2.0 },
      { id: "delta", name: "Delta Velorum", x: 57.5, y: 46.1, size: 1.7 },
      { id: "kappa", name: "Kappa Velorum", x: 60.4, y: 48.0, size: 1.4 },
      { id: "mu", name: "Mu Velorum", x: 63.1, y: 50.7, size: 1.3 },
      { id: "lambda", name: "Lambda Velorum", x: 59.0, y: 51.4, size: 1.5 },
      { id: "psi", name: "Psi Velorum", x: 54.2, y: 49.6, size: 1.1 },
      { id: "phi", name: "Phi Velorum", x: 57.0, y: 52.9, size: 1.2 },
    ],
    connections: [
      ["gamma", "delta"],
      ["delta", "kappa"],
      ["kappa", "mu"],
      ["mu", "lambda"],
      ["lambda", "phi"],
      ["phi", "psi"],
      ["psi", "gamma"],
      ["delta", "lambda"],
    ],
  }),
  createConstellation({
    id: "eridanus",
    name: "Eridanus",
    accent: "#7cc8ff",
    headline: "A star-river dropping toward the far southern sky.",
    region: "Southern river chain",
    bestSeen: "November to January",
    knownFor: "Its long descent away from Orion.",
    description:
      "Eridanus is another path-constellation: a current of stars that begins near Orion and runs deep into the south.",
    label: { x: 76.8, y: 26.0, align: "start" },
    stars: [
      { id: "cursa", name: "Cursa", x: 76.5, y: 28.6, size: 1.3 },
      { id: "zaurak", name: "Zaurak", x: 79.0, y: 31.4, size: 1.5 },
      { id: "rana", name: "Rana", x: 82.4, y: 34.8, size: 1.3 },
      { id: "azha", name: "Azha", x: 84.5, y: 38.6, size: 1.2 },
      { id: "acamar", name: "Acamar", x: 87.2, y: 43.0, size: 1.4 },
      { id: "achernar", name: "Achernar", x: 91.4, y: 51.6, size: 2.1 },
      { id: "beid", name: "Beid", x: 89.1, y: 47.2, size: 1.1 },
    ],
    connections: [
      ["cursa", "zaurak"],
      ["zaurak", "rana"],
      ["rana", "azha"],
      ["azha", "acamar"],
      ["acamar", "beid"],
      ["beid", "achernar"],
    ],
  }),
  createConstellation({
    id: "cetus",
    name: "Cetus",
    accent: "#ff9c7f",
    headline: "A sprawling sea monster with a heavy southern body.",
    region: "Equatorial autumn sky",
    bestSeen: "October to December",
    knownFor: "Mira and its broad, sea-beast outline.",
    description:
      "Cetus spreads wide and low. It works best in the map as a heavy southern silhouette with one bright, volatile heart.",
    label: { x: 84.0, y: 37.2, align: "start" },
    stars: [
      { id: "menkar", name: "Menkar", x: 83.8, y: 40.2, size: 1.7 },
      { id: "mira", name: "Mira", x: 86.8, y: 44.0, size: 1.7 },
      { id: "kaffal", name: "Kaffaljidhma", x: 88.8, y: 40.9, size: 1.1 },
      { id: "deneb", name: "Deneb Kaitos", x: 91.6, y: 47.3, size: 1.8 },
      { id: "baten", name: "Baten Kaitos", x: 94.2, y: 44.5, size: 1.2 },
    ],
    connections: [
      ["menkar", "mira"],
      ["mira", "deneb"],
      ["kaffal", "deneb"],
      ["deneb", "baten"],
      ["menkar", "kaffal"],
    ],
  }),
];

export const CONSTELLATIONS_BY_ID = Object.fromEntries(
  CONSTELLATIONS.map((constellation) => [constellation.id, constellation]),
);

export const getConstellationCentroid = (constellation) => {
  const stars = Array.isArray(constellation?.stars) ? constellation.stars : [];
  if (!stars.length) {
    return { x: VIEWBOX_WIDTH / 2, y: VIEWBOX_HEIGHT / 2 };
  }

  const total = stars.reduce(
    (accumulator, star) => ({
      x: accumulator.x + star.x,
      y: accumulator.y + star.y,
    }),
    { x: 0, y: 0 },
  );

  return {
    x: total.x / stars.length,
    y: total.y / stars.length,
  };
};

export const buildAmbientStars = (count = 180, seed = 7) => {
  let state = seed;
  const nextRandom = () => {
    state = (state * 9301 + 49297) % 233280;
    return state / 233280;
  };

  return Array.from({ length: count }, (_, index) => ({
    id: `ambient-${index + 1}`,
    x: 2 + nextRandom() * 96,
    y: 2 + nextRandom() * 56,
    size: 0.12 + nextRandom() * 0.42,
    opacity: 0.24 + nextRandom() * 0.68,
    duration: 2.8 + nextRandom() * 5.2,
    delay: nextRandom() * 4.5,
    depth: nextRandom(),
  }));
};
