IF OBJECT_ID(N'Users', N'U') IS NULL
BEGIN
    CREATE TABLE Users
    (
        Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
        Email NVARCHAR(255) NOT NULL UNIQUE,
        Name NVARCHAR(120) NOT NULL,
        HashedPassword NVARCHAR(255) NOT NULL,
        IsAdmin BIT NOT NULL CONSTRAINT DF_Users_IsAdmin DEFAULT(0),
        Role NVARCHAR(20) NOT NULL CONSTRAINT DF_Users_Role DEFAULT('user'),
        CreatedAtUtc DATETIME2 NOT NULL CONSTRAINT DF_Users_CreatedAtUtc DEFAULT(SYSUTCDATETIME())
    );
END;
