IF OBJECT_ID(N'Users', N'U') IS NULL
BEGIN
    CREATE TABLE Users
    (
        Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
        Email NVARCHAR(255) NOT NULL UNIQUE,
        Name NVARCHAR(120) NOT NULL,
        DisplayName NVARCHAR(120) NULL,
        AvatarUrl NVARCHAR(500) NULL,
        Bio NVARCHAR(500) NULL,
        HashedPassword NVARCHAR(255) NOT NULL,
        IsAdmin BIT NOT NULL CONSTRAINT DF_Users_IsAdmin DEFAULT(0),
        Role NVARCHAR(20) NOT NULL CONSTRAINT DF_Users_Role DEFAULT('user'),
        CreatedAtUtc DATETIME2 NOT NULL CONSTRAINT DF_Users_CreatedAtUtc DEFAULT(SYSUTCDATETIME())
    );
END;

IF COL_LENGTH('Users', 'DisplayName') IS NULL
BEGIN
    ALTER TABLE Users ADD DisplayName NVARCHAR(120) NULL;
END;

IF COL_LENGTH('Users', 'AvatarUrl') IS NULL
BEGIN
    ALTER TABLE Users ADD AvatarUrl NVARCHAR(500) NULL;
END;

IF COL_LENGTH('Users', 'Bio') IS NULL
BEGIN
    ALTER TABLE Users ADD Bio NVARCHAR(500) NULL;
END;
