import { Vector3 } from "three";
import { PLANET_TEXTURES, resolvePlanetTexture } from "@/utils/planetUtils";
import earthDayMap from "@/assets/planets/2k_earth_daymap.jpg";

export const BODY_DEFINITIONS = [
  {
    id: "sun",
    name: "Sun",
    radius: 2.2,
    orbitRadius: 0,
    orbitSpeed: 0,
    rotationSpeed: 0.08,
    phase: 0,
    accent: "#ffd36e",
    distance: "0 km",
    day: "25-35 Earth days",
    year: "Center of the system",
    moons: "N/A",
    temperature: "5,500\u00B0C surface",
    description:
      "The star that holds the whole system together. Every orbit, season, and sunrise starts here.",
    textureUrl: PLANET_TEXTURES.sun,
    isStar: true,
  },
  {
    id: "mercury",
    name: "Mercury",
    radius: 0.42,
    orbitRadius: 4.5,
    orbitSpeed: 1.55,
    rotationSpeed: 0.18,
    phase: 0.7,
    accent: "#d1b08d",
    distance: "57.9 million km",
    day: "58.6 Earth days",
    year: "88 days",
    moons: "0",
    temperature: "-173\u00B0C to 427\u00B0C",
    description:
      "The fastest planet around the Sun. Tiny, rocky, and packed with extreme day-night temperature swings.",
    textureUrl: resolvePlanetTexture("Mercury"),
  },
  {
    id: "venus",
    name: "Venus",
    radius: 0.65,
    orbitRadius: 6.5,
    orbitSpeed: 1.18,
    rotationSpeed: 0.06,
    phase: 1.2,
    accent: "#f1c58d",
    distance: "108.2 million km",
    day: "243 Earth days",
    year: "225 days",
    moons: "0",
    temperature: "465\u00B0C average",
    description:
      "Earth's size twin, but wrapped in thick clouds and runaway heat. It shines bright but hides a brutal surface.",
    textureUrl: resolvePlanetTexture("Venus"),
  },
  {
    id: "earth",
    name: "Earth",
    radius: 0.7,
    orbitRadius: 8.7,
    orbitSpeed: 1,
    rotationSpeed: 0.42,
    phase: 2,
    accent: "#68c6ff",
    distance: "149.6 million km",
    day: "24 hours",
    year: "365 days",
    moons: "1",
    temperature: "-89\u00B0C to 58\u00B0C",
    description:
      "The reference point for everything else. Ocean, atmosphere, life, and the place VELA helps you explore from.",
    textureUrl: earthDayMap,
  },
  {
    id: "mars",
    name: "Mars",
    radius: 0.55,
    orbitRadius: 11.4,
    orbitSpeed: 0.82,
    rotationSpeed: 0.38,
    phase: 2.6,
    accent: "#ff8d63",
    distance: "227.9 million km",
    day: "24.6 hours",
    year: "687 days",
    moons: "2",
    temperature: "-125\u00B0C to 20\u00B0C",
    description:
      "The red planet. Dry, dusty, and still the most realistic target when people talk about future exploration.",
    textureUrl: resolvePlanetTexture("Mars"),
  },
  {
    id: "jupiter",
    name: "Jupiter",
    radius: 1.3,
    orbitRadius: 15.8,
    orbitSpeed: 0.44,
    rotationSpeed: 0.68,
    phase: 3,
    accent: "#f4c9a6",
    distance: "778.5 million km",
    day: "9.9 hours",
    year: "11.9 years",
    moons: "95+",
    temperature: "-145\u00B0C cloud tops",
    description:
      "The giant of the system. Enormous storms, dozens of moons, and enough gravity to dominate the outer planets.",
    textureUrl: resolvePlanetTexture("Jupiter"),
  },
  {
    id: "saturn",
    name: "Saturn",
    radius: 1.15,
    orbitRadius: 20.5,
    orbitSpeed: 0.32,
    rotationSpeed: 0.6,
    phase: 3.7,
    accent: "#f3deb0",
    distance: "1.43 billion km",
    day: "10.7 hours",
    year: "29.5 years",
    moons: "140+",
    temperature: "-178\u00B0C average",
    description:
      "The signature ring world. It is lighter than water by density, but visually it is the most dramatic planet in the system.",
    textureUrl: resolvePlanetTexture("Saturn"),
    ringUrl: PLANET_TEXTURES.saturnRing,
    ringTilt: 0.5,
    ringInnerRadius: 1.45,
    ringOuterRadius: 2.15,
  },
  {
    id: "uranus",
    name: "Uranus",
    radius: 0.92,
    orbitRadius: 25.2,
    orbitSpeed: 0.22,
    rotationSpeed: 0.34,
    phase: 4.3,
    accent: "#96f1ff",
    distance: "2.87 billion km",
    day: "17.2 hours",
    year: "84 years",
    moons: "27",
    temperature: "-224\u00B0C average",
    description:
      "An ice giant tipped on its side. Its strange axial tilt makes its seasons unlike any other planet here.",
    textureUrl: resolvePlanetTexture("Uranus"),
  },
  {
    id: "neptune",
    name: "Neptune",
    radius: 0.9,
    orbitRadius: 29.6,
    orbitSpeed: 0.18,
    rotationSpeed: 0.35,
    phase: 5.1,
    accent: "#6ca7ff",
    distance: "4.5 billion km",
    day: "16.1 hours",
    year: "164.8 years",
    moons: "16",
    temperature: "-214\u00B0C average",
    description:
      "The outer blue giant. Dark, cold, and violently windy, with some of the fastest storms in the solar system.",
    textureUrl: resolvePlanetTexture("Neptune"),
  },
];

export const BODY_LOOKUP = Object.fromEntries(
  BODY_DEFINITIONS.map((body) => [body.id, body]),
);

const planetIcon = (fileName) =>
  new URL(`../../assets/icons/planets/${fileName}`, import.meta.url).href;

export const PLANET_ICON_URLS = {
  sun: planetIcon("sun.svg"),
  mercury: planetIcon("mercury.svg"),
  venus: planetIcon("venus.svg"),
  earth: planetIcon("earth.svg"),
  mars: planetIcon("mars.svg"),
  jupiter: planetIcon("jupiter.svg"),
  saturn: planetIcon("saturn.svg"),
  uranus: planetIcon("uranus.svg"),
  neptune: planetIcon("neptune.svg"),
};

export const CAMERA_HOME = new Vector3(0, 11, 31);
export const TARGET_HOME = new Vector3(0, 0, 0);
